name = "adagb"
description = "GAME BOY COLOR Emulator written in Ada"
version = "0.1.0-dev"

authors = ["bubio"]
maintainers = ["bubio <bubio66@gmail.com>"]
maintainers-logins = ["bubio"]
licenses = "MIT"
website = ""
tags = ["emulator", "ada", "gbc"]

executables = ["adagb"]

[[depends-on]]
df_imgui = "=0.1.0"
